name: CI
on:
  push:
    branches: [ test_ci ]
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo Hello World!
        
      - name: Run another script
        run: This is a new command.
        
        
  
  
  
