name: CI
on:
  push:
    branches: [ feature ]
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: List all files
        run: ls
        
        
  
  
  
