name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{env.NODE_VERSION}}


      - name: npm install build and test
        run: 
          npm install
          nmp run build --if-present
          npx jest

      - name: upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: MISSION3   
          path: .
          


      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME }}   
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}  
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH }}  
        run: 


  
        
        
  
  
  
